# Generated by Django 4.2.7 on 2023-11-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
